version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db 
      - DB_NAME=devdb 
      - DB_USER=devuser 
      - DB_PASS=changeme
    depends_on: #tells docker-compose that the app service will wait on db service to start first
      - db  
  
  db:
    image: postgres:13-alpine
    volumes: 
      - dev-db-data:/var/lib/postgresql/data
    environment: #to set the intial database configuration for new db service for local development database
      - POSTGRES_DB=devdb 
      - POSTGRES-USER=devuser
      - POSTGRES_PASSWORD=changeme


volumes:
  dev-db-data: